// Code generated by logcopter-gen; DO NOT EDIT.

package dev

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.devctl.cmd.devctl.cmds.dev")
