# Example devctl configuration
plugins:
  - id: ok
    path: python3
    args:
      - ./testdata/plugins/ok-python/plugin.py
    priority: 10
# strictness: warn   # or "error" (or use --strict)

# Pipeline example (supports config.mutate + launch.plan)
# plugins:
#   - id: pipeline
#     path: python3
#     args:
#       - ./testdata/plugins/pipeline/plugin.py
#     priority: 10

# Supervision example (launches a local python http.server with health check)
# plugins:
#   - id: http
#     path: python3
#     args:
#       - ./testdata/plugins/http-service/plugin.py
#     priority: 10
