// Code generated by logcopter-gen; DO NOT EDIT.

package operator

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.devctl.pkg.operator")
